---
- hosts: all
  sudo: true
  vars:
      home: /home/vagrant
      document_root: /vagrant
      mw_dir: /var/www/html/w
  pre_tasks:
      - name: Symlink sh to bash rather than dash
        file: src=/bin/bash dest=/bin/sh state=link force=true
      - name: Update apt cache and optionally upgrade
        apt:
          update_cache=yes
          cache_valid_time=7200
          #upgrade=yes # Uncomment this to force full upgrade!
      - name: Install stuff from Aptitude
        apt: name={{ item }} state=installed
        with_items:
         - git
         - tig
         - vim
         - bash-completion # Not included in the docker image
         - make
         - tree
         - htop
         - tmux
         - man-db
         - python-mysqldb
  roles:
      - { role: dotfiles, tags: ['dotfiles'] }
      - { role: php, tags: ['php'] }
      - { role: nginx, tags: ['nginx'] }
      - { role: travis, tags: ['travis'] }
      - { role: mysql, tags: ['mysql', 'travis'] }
      - { role: mediawiki, tags: ['mediawiki', 'travis'] }
      - { role: semantic_mediawiki, tags: ['semantic_mediawiki', 'travis'] }
      - { role: rdfio, tags: ['rdfio', 'travis'] }
