---
- name: Install stuff from Aptitude
  apt: name={{ item }} state=installed
  with_items:
    - apache2
    - mysql-server
    - php5 
    - libapache2-mod-php5
    - php5-mysql
    - php5-cli
    - php5-gd
    - php5-xdebug
    - php5-json
    - php5-xsl
    - php-apc
    - phpunit
    - composer
  notify: restart apache2
