---
- name: Download MediaWiki
  get_url:
    url=http://releases.wikimedia.org/mediawiki/{{mwver_major}}/mediawiki-{{mwver_minor}}.tar.gz
    dest=/vagrant/mediawiki-{{mwver_minor}}.tar.gz
    mode=0440
- name: Unpack MediaWiki tarball
  unarchive:
    src=/vagrant/mediawiki-{{mwver_minor}}.tar.gz
    dest=/var/www/html
    copy=no # Don't copy from local machine
- name: Rename MediaWiki folder
  command:
    creates=/var/www/html/w
    mv /var/www/html/mediawiki-{{mwver_minor}} /var/www/html/w
- name: Create MySQL database
  mysql_db:
    name=mw
    state=present
- name: Create MySQL user
  mysql_user:
    name=mw
    password=changethis
    priv=mw.*:ALL
    state=present
## After downloading the LocalSettings.php file, copy it to the wiki folder:
#cp ~/Downloads/LocalSettings.php .
#
## Enter your new wiki:
#firefox http://localhost/mw123/
#
## Head over to the SMW website:
#firefox http://semantic-mediawiki.org
## Click the "orange button" saying "SMW 1.9.2"
## Locate and click the link to the "installing" instructions.
#
## Open the composer intall instructions
#firefox https://getcomposer.org/doc/00-intro.md#installation-nix
#
## Get Composer
#curl -sS https://getcomposer.org/installer | php
#
## Check that you have the phar file at hand
#ll *.phar
#
## Install SMW via composer
#php composer.phar require mediawiki/semantic-media-wiki "~1.9"
#
## Go to the RDFIO page:
#firefox http://www.mediawiki.org/wiki/Extension:RDFIO
#
## Install the dependency, Wiki Object Model:
#cd extensions
#svn checkout http://svn.wikimedia.org/svnroot/mediawiki/trunk/extensions/WikiObjectModel
#
## Add the following line to LocalSettings.php:
#include_once("$IP/extensions/WikiObjectModel/WikiObjectModel.php");
#
## You can alternatively just run this command:
#echo 'include_once("$IP/extensions/WikiObjectModel/WikiObjectModel.php");' >> LocalSettings.php
#
## Install dependency #2: ARC2:
#cd extensions/SemanticMediaWiki
#mkdir libs
#cd libs
#git clone https://github.com/semsol/arc2.git arc
#
## Install RDFIO
#cd wiki/extensions
#git clone https://github.com/samuell/RDFIO.git
#
## Add the following lines to your LocalSettings.php:
#include_once("$IP/extensions/RDFIO/RDFIO.php");
#$smwgOWLFullExport = true;
#
## Alternatively, just run this command:
#echo 'include_once("$IP/extensions/RDFIO/RDFIO.php");' >> LocalSettings.php
#echo '$smwgOWLFullExport = true;' >> LocalSettings.php
#
## Log in to your wiki as a super user
#
## Open the page MediaWiki:Sidebar
#firefox http://localhost/mw123/MediaWiki:Sidebar
#
## Edit the page and paste the following code, and save:
#* Semantic Tools
#** Special:ARC2Admin|ARC2 Admin
#** Special:RDFImport|RDF Import
#** Special:SPARQLEndpoint|SPARQL Endpoint
#** Special:SPARQLImport|SPARQL Import
#
## Go to the Special:ARC2Admin page, and hit the "install" button
#firefox http://localhost/mw123/Special:Arc2Store
#
## Go to The "RDF Import" page, by clicking in the menu to the left
#
## Import some test data
#
## Check in the "Recent changes" if something has been installed!
