---
- name: Download MediaWiki
  get_url:
    url=http://releases.wikimedia.org/mediawiki/{{mwver_major}}/mediawiki-{{mwver_minor}}.tar.gz
    dest=/vagrant/mediawiki-{{mwver_minor}}.tar.gz
    mode=0440
- name: Unpack MediaWiki tarball
  unarchive:
    src=/vagrant/mediawiki-{{mwver_minor}}.tar.gz
    dest=/var/www/html
    copy=no # Don't copy from local machine
- name: Rename MediaWiki folder
  command:
    creates=/var/www/html/w
    mv /var/www/html/mediawiki-{{mwver_minor}} /var/www/html/w
- name: Create MySQL database
  mysql_db:
    name=mw
    state=present
- name: Create MySQL user
  mysql_user:
    name=mw
    password=changethis
    priv=mw.*:ALL
    state=present
- name: Change user & group for wiki folder
  file:
    path=/var/www/html/w
    owner=www-data
    group=www-data
    recurse=yes
- name: Install MediaWiki database
  command:
      php /var/www/html/w/maintenance/install.php --scriptpath=/w --dbname=mw --dbuser=mw --dbpass=changethis --installdbuser=root --installdbpass= --pass=changethis MW admin
      creates=/var/www/html/w/LocalSettings.php
- name: Change user & group of LocalSettings.php
  file:
    path=/var/www/html/w/LocalSettings.php
    owner=www-data
    group=www-data
- name: Print location of wiki
  debug:
    msg: "You can see your wiki, by entering in a browser: http://localhost:8080/w"
