---
- name: Import some initial wiki content
  shell: >
    php {{ mw_dir }}/maintenance/importDump.php /vagrant/roles/rdfio/files/wiki_content.xml
- name: Install RDFIO including dependencies via composer
  composer:
    command=require
    arguments="rdfio/rdfio --update-no-dev"
    working_dir={{ mw_dir }}
- name: Activate full OWL export, as needed by RDFIO
  lineinfile:
    line='$smwgOWLFullExport = true;'
    dest={{ mw_dir }}/LocalSettings.php
    state=present
- name: Change user & group for wiki folder
  file:
    path=/var/www/html/w
    owner=www-data
    group=www-data
    recurse=yes
- name: Inform about manual steps needed to complete installation
  debug: "msg='MANUAL STEPS NEEDED TO COMPLETE INSTALLATION: 1. Visit this page on the wiki: http://localhost:8080/w/index.php/Special:RDFIOAdmin, 2. Login with 'Admin' and 'changethis' 3. Click the Setup button.'"
