---
- name: Check out the WikiObjectModel extension
  git:
    repo=https://github.com/wikimedia/mediawiki-extensions-WikiObjectModel.git
    dest={{ mw_dir }}/extensions/WikiObjectModel
- name: Activate WikiObjectModel in MediaWiki settings file
  lineinfile:
    line='include_once("$IP/extensions/WikiObjectModel/WikiObjectModel.php");'
    dest={{ mw_dir }}/LocalSettings.php
    state=present
- name: Install ARC2
  composer:
    command=require
    arguments="semsol/arc2 v2.2.4 --update-no-dev"
    working_dir={{ mw_dir }}
- name: Check out the RDFIO
  git:
    repo=https://github.com/samuell/RDFIO.git
    dest={{ mw_dir }}/extensions/RDFIO
    version=update-to-latest-mw-smw
- name: Activate RDFIO in MediaWiki settings file
  lineinfile:
    line='include_once("$IP/extensions/RDFIO/RDFIO.php");'
    dest={{ mw_dir }}/LocalSettings.php
    state=present
- name: Activate full OWL export, as needed by RDFIO
  lineinfile:
    line='$smwgOWLFullExport = true;'
    dest={{ mw_dir }}/LocalSettings.php
    state=present
- name: Import some initial wiki content
  shell: >
    /usr/bin/php {{ mw_dir }}/maintenance/importDump.php /vagrant/roles/rdfio/files/wiki_content.xml
#### Go to the Special:ARC2Admin page, and hit the "install" button
###firefox http://localhost/mw123/Special:Arc2Store
###
#### Go to The "RDF Import" page, by clicking in the menu to the left
###
#### Import some test data
###
#### Check in the "Recent changes" if something has been installed!
